"""add imageurl to staff table

Revision ID: 05686707e641
Revises: 9b67130c1f11
Create Date: 2024-05-23 16:03:21.492791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05686707e641'
down_revision = '9b67130c1f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'img_url')
    # ### end Alembic commands ###
